# Generated by Django 5.2.8 on 2026-07-28 00:42

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0007_remove_sicarrecord_geometry_new_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sicarrecord',
            index=models.Index(django.db.models.functions.text.Upper('car_number'), name='idx_sicar_car_number_upper'),
        ),
    ]
