# Generated by Django 5.2.8 on 2026-08-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_system', '0009_declaredhydrography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaredhydrography',
            name='pending',
            field=models.CharField(db_column='des_condic', max_length=100, verbose_name='Pendentes de Declaração'),
        ),
    ]
