# Generated by Django 5.2.8 on 2025-12-01 18:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deforestation_fires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deforestationmapbiomas',
            name='geometry_new',
        ),
        migrations.AddField(
            model_name='deforestationmapbiomas',
            name='usable_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674),
        ),
    ]
