# Generated by Django 5.2.8 on 2025-12-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deforestation_fires', '0002_remove_deforestationmapbiomas_geometry_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestationmapbiomas',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados'),
        ),
    ]
