# Generated by Django 5.2.8 on 2026-02-09 17:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deforestation_fires', '0003_alter_deforestationmapbiomas_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embargoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
                ('usable_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674)),
                ('area_m2', models.FloatField(blank=True, db_column='area_m2', null=True, verbose_name='Área (m²)')),
                ('area_ha', models.FloatField(blank=True, db_column='area_ha', null=True, verbose_name='Área (ha)')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('property_name', models.CharField(db_column='nome_imove', max_length=100, verbose_name='Nome do imovel')),
                ('type_area', models.CharField(db_column='tipo_area', max_length=70, verbose_name='Tipo de area')),
                ('number_infraction_act', models.CharField(db_column='num_auto_i', max_length=70, verbose_name='numero do ato de infracao')),
                ('nome_embargado', models.CharField(db_column='nome_embar', max_length=100, verbose_name='Nome do embargado')),
                ('cpf_cnpj_embargado', models.CharField(db_column='cpf_cnpj_e', max_length=70, verbose_name='CPF/CNPJ do embargado')),
                ('control_unity', models.CharField(db_column='unidade_c', max_length=100, verbose_name='Unidade controladora')),
                ('process_number', models.CharField(db_column='num_proce', max_length=70, verbose_name='Numero do processo')),
                ('act_description', models.CharField(db_column='des_tad', max_length=100, verbose_name='Descricao do ato de infracao')),
                ('infraction_description', models.CharField(db_column='des_infrac', max_length=100, verbose_name='Descricao do infracao')),
                ('embargoe_date', models.CharField(db_column='data_embarg', max_length=70, verbose_name='Data do embargado')),
                ('priting_date', models.CharField(db_column='data_impres', max_length=70, verbose_name='Data de impressao')),
                ('hash_id', models.CharField(blank=True, db_column='hash_id', max_length=64, null=True, unique=True, verbose_name='Hash ID')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Embargoes',
                'verbose_name_plural': 'Embargoes',
                'db_table': 'tb_embargoes',
            },
        ),
    ]
