# Generated by Django 5.2.8 on 2026-02-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deforestation_fires', '0004_embargoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embargoes',
            name='property_name',
            field=models.CharField(db_column='nome_imove', max_length=250, verbose_name='Nome do imovel'),
        ),
    ]
