# Generated by Django 5.2.8 on 2026-02-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deforestation_fires', '0005_alter_embargoes_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embargoes',
            name='control_unity',
            field=models.CharField(db_column='unid_contr', max_length=100, verbose_name='Unidade controladora'),
        ),
    ]
