# Generated by Django 5.2.8 on 2026-02-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deforestation_fires', '0006_alter_embargoes_control_unity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embargoes',
            name='act_description',
            field=models.CharField(db_column='des_tad', max_length=300, verbose_name='Descricao do ato de infracao'),
        ),
        migrations.AlterField(
            model_name='embargoes',
            name='control_unity',
            field=models.CharField(db_column='unid_contr', max_length=300, verbose_name='Unidade controladora'),
        ),
        migrations.AlterField(
            model_name='embargoes',
            name='infraction_description',
            field=models.CharField(db_column='des_infrac', max_length=300, verbose_name='Descricao do infracao'),
        ),
        migrations.AlterField(
            model_name='embargoes',
            name='nome_embargado',
            field=models.CharField(db_column='nome_embar', max_length=300, verbose_name='Nome do embargado'),
        ),
        migrations.AlterField(
            model_name='embargoes',
            name='property_name',
            field=models.CharField(db_column='nome_imove', max_length=300, verbose_name='Nome do imovel'),
        ),
    ]
