# Generated by Django 5.2.8 on 2026-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deforestation_fires', '0007_alter_embargoes_act_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embargoes',
            name='embargoe_date',
            field=models.CharField(db_column='dat_embarg', max_length=70, verbose_name='Data do embargado'),
        ),
        migrations.AlterField(
            model_name='embargoes',
            name='priting_date',
            field=models.CharField(db_column='dat_impres', max_length=70, verbose_name='Data de impressao'),
        ),
        migrations.AlterField(
            model_name='embargoes',
            name='process_number',
            field=models.CharField(db_column='num_process', max_length=70, verbose_name='Numero do processo'),
        ),
    ]
