# Generated by Django 5.2.8 on 2026-02-10 19:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deforestation_fires', '0008_alter_embargoes_embargoe_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
                ('usable_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674)),
                ('area_m2', models.FloatField(blank=True, db_column='area_m2', null=True, verbose_name='Área (m²)')),
                ('area_ha', models.FloatField(blank=True, db_column='area_ha', null=True, verbose_name='Área (ha)')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('identification', models.CharField(db_column='main_class', max_length=100, verbose_name='Identificação')),
                ('image_date', models.CharField(db_column='image_date', max_length=70, verbose_name='Data da imagem')),
                ('year', models.CharField(db_column='year', max_length=70, verbose_name='Ano')),
                ('satelite', models.CharField(db_column='satelite', max_length=100, verbose_name='Satélite')),
                ('hash_id', models.CharField(blank=True, db_column='hash_id', max_length=64, null=True, unique=True, verbose_name='Hash ID')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Prodes',
                'verbose_name_plural': 'Prodes',
                'db_table': 'tb_prodes',
            },
        ),
    ]
