# Generated by Django 5.2.8 on 2025-12-01 18:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturatins', '0004_municipalboundaries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conservationunits',
            name='geometry_new',
        ),
        migrations.RemoveField(
            model_name='municipalboundaries',
            name='geometry_new',
        ),
        migrations.RemoveField(
            model_name='paths',
            name='geometry_new',
        ),
        migrations.RemoveField(
            model_name='quilombolas',
            name='geometry_new',
        ),
        migrations.AddField(
            model_name='conservationunits',
            name='usable_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674),
        ),
        migrations.AddField(
            model_name='municipalboundaries',
            name='usable_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674),
        ),
        migrations.AddField(
            model_name='paths',
            name='usable_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674),
        ),
        migrations.AddField(
            model_name='quilombolas',
            name='usable_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674),
        ),
    ]
