# Generated by Django 5.2.8 on 2025-11-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_filemanagement_indigenous_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='quilombolas_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de Quilombolas.', null=True, upload_to='documents/', verbose_name='Documentos Quilombolas'),
        ),
    ]
