# Generated by Django 5.2.8 on 2025-11-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_filemanagement_paths_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='conservation_units_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de Unidades de Conservação.', null=True, upload_to='documents/', verbose_name='Documentos Unidades de Conservação'),
        ),
    ]
