# Generated by Django 5.2.8 on 2025-11-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0007_filemanagement_sigef_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='ruralsettlement_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de Assentamento Rural.', null=True, upload_to='documents/', verbose_name='Documentos Assentamento Rural'),
        ),
    ]
