# Generated by Django 5.2.8 on 2025-11-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0008_filemanagement_ruralsettlement_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='deforestation_mapbiomas_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de Mapa de Deforestação.', null=True, upload_to='documents/', verbose_name='Documentos Mapa de Deforestação'),
        ),
        migrations.AddField(
            model_name='filemanagement',
            name='snic_total_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de SNIC Total.', null=True, upload_to='documents/', verbose_name='Documentos SNIC Total'),
        ),
    ]
