# Generated by Django 5.2.8 on 2026-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0009_filemanagement_deforestation_mapbiomas_zip_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='highways_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de Highways.', null=True, upload_to='documents/', verbose_name='Documentos Highways'),
        ),
    ]
