# Generated by Django 5.2.8 on 2026-02-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0010_filemanagement_highways_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='ipuca_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de Ipuca.', null=True, upload_to='documents/', verbose_name='Documentos Ipuca'),
        ),
    ]
