# Generated by Django 5.2.8 on 2026-02-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0011_filemanagement_ipuca_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='adm_embargos_ibama_a_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de Embargos IBAMA A.', null=True, upload_to='documents/', verbose_name='Documentos Embargos IBAMA A'),
        ),
    ]
