# Generated by Django 5.2.8 on 2026-07-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0013_filemanagement_prodes_zip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('database_size_bytes', models.BigIntegerField(verbose_name='Tamanho do Banco (bytes)')),
                ('disk_used_bytes', models.BigIntegerField(verbose_name='Disco Utilizado (bytes)')),
                ('disk_total_bytes', models.BigIntegerField(verbose_name='Disco Total (bytes)')),
            ],
            options={
                'verbose_name': 'Snapshot de Armazenamento',
                'verbose_name_plural': 'Snapshots de Armazenamento',
                'db_table': 'tb_armazenamento_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
    ]
