# Generated by Django 5.2.8 on 2026-07-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0014_storagesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagesnapshot',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Servidor'),
        ),
    ]
