# Generated by Django 5.2.8 on 2026-07-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0015_storagesnapshot_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerFieldToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('campo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coluna do Resultado da Análise',
                'verbose_name_plural': 'Colunas do Resultado da Análise',
                'db_table': 'tb_layer_field_toggle',
                'constraints': [models.UniqueConstraint(fields=('modelo', 'campo'), name='uniq_layer_field_toggle')],
            },
        ),
    ]
