# Generated by Django 5.2.8 on 2026-07-27 22:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0016_layerfieldtoggle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cor', models.CharField(default='#607D8B', max_length=7)),
                ('ativo', models.BooleanField(default=False)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documents/custom_layers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_layers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base de Dados Customizada',
                'verbose_name_plural': 'Bases de Dados Customizadas',
                'db_table': 'tb_custom_layer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomLayerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
                ('usable_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674)),
                ('area_m2', models.FloatField(blank=True, db_column='area_m2', null=True, verbose_name='Área (m²)')),
                ('area_ha', models.FloatField(blank=True, db_column='area_ha', null=True, verbose_name='Área (ha)')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('atributos', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='control_panel.customlayer')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Feição de Base Customizada',
                'verbose_name_plural': 'Feições de Bases Customizadas',
                'db_table': 'tb_custom_layer_feature',
            },
        ),
        migrations.CreateModel(
            name='CustomLayerColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coluna_origem', models.CharField(help_text='Nome da coluna no shapefile original', max_length=100)),
                ('rotulo', models.CharField(max_length=150)),
                ('incluir', models.BooleanField(default=True, help_text='Aparece no resultado da análise de sobreposição')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='control_panel.customlayer')),
            ],
            options={
                'db_table': 'tb_custom_layer_column',
                'ordering': ['ordem', 'id'],
                'constraints': [models.UniqueConstraint(fields=('layer', 'coluna_origem'), name='uniq_custom_layer_column')],
            },
        ),
    ]
