# Generated by Django 5.2.8 on 2026-08-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0017_customlayer_customlayerfeature_customlayercolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customlayerfeature',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='customlayercolumn',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='customlayerfeature',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customlayerfeature',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CustomLayer',
        ),
        migrations.DeleteModel(
            name='CustomLayerColumn',
        ),
        migrations.DeleteModel(
            name='CustomLayerFeature',
        ),
    ]
