# Generated by Django 5.2.8 on 2026-08-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0018_remove_customlayerfeature_layer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemanagement',
            name='hydrography_zip_file',
            field=models.FileField(blank=True, help_text='Arquivo ZIP contendo dados da Área de Hidrografia Declarada.', null=True, upload_to='documents/', verbose_name='Documentos Hidrografia Declarada'),
        ),
    ]
