# Generated by Django 5.2.8 on 2026-02-06 12:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.TextField(db_column='coordenadas_geograficas', verbose_name='Coordenadas Geográficas')),
                ('usable_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674)),
                ('area_m2', models.FloatField(blank=True, db_column='area_m2', null=True, verbose_name='Área (m²)')),
                ('area_ha', models.FloatField(blank=True, db_column='area_ha', null=True, verbose_name='Área (ha)')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Dados')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('name_2011', models.CharField(blank=True, db_column='NOME_2011', max_length=255, null=True, verbose_name='Nome 2011')),
                ('clas_2011', models.CharField(blank=True, db_column='CLAS_2011', max_length=255, null=True, verbose_name='Classificação 2011')),
                ('hash_id', models.CharField(blank=True, db_column='hash_id', max_length=64, null=True, unique=True, verbose_name='Hash ID')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Rodovia',
                'verbose_name_plural': 'Rodovias',
                'db_table': 'tb_highways',
            },
        ),
    ]
