# Generated by Django 5.2.8 on 2026-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highways',
            name='clas_2011',
            field=models.CharField(blank=True, db_column='CLAS_2011', max_length=255, null=True, verbose_name='Tipo da via'),
        ),
        migrations.AlterField(
            model_name='highways',
            name='name_2011',
            field=models.CharField(blank=True, db_column='NOME_2011', max_length=255, null=True, verbose_name='Nome da via'),
        ),
    ]
