# Generated by Django 5.2.8 on 2026-07-16 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(blank=True, choices=[('estudar', 'Estudar'), ('analisar_propriedades', 'Analisar propriedades'), ('agilizar_demanda', 'Agilizar demanda de trabalho'), ('outro', 'Outro')], max_length=30, verbose_name='Objetivo na plataforma')),
                ('objetivo_outro', models.CharField(blank=True, max_length=150, verbose_name='Objetivo (outro)')),
                ('profissao', models.CharField(blank=True, choices=[('engenheiro_agronomo', 'Engenheiro(a) Agrônomo(a)'), ('engenheiro_ambiental', 'Engenheiro(a) Ambiental'), ('engenheiro_florestal', 'Engenheiro(a) Florestal'), ('topografo', 'Topógrafo(a)'), ('geologo', 'Geólogo(a)'), ('advogado', 'Advogado(a)'), ('produtor_rural', 'Produtor(a) Rural'), ('consultor_ambiental', 'Consultor(a) Ambiental'), ('estudante', 'Estudante'), ('outro', 'Outro')], max_length=30, verbose_name='Profissão')),
                ('profissao_outro', models.CharField(blank=True, max_length=150, verbose_name='Profissão (outra)')),
                ('onboarding_completo', models.BooleanField(default=False, verbose_name='Onboarding concluído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
                'db_table': 'tb_usuario_perfil',
            },
        ),
    ]
