# Generated by Django 5.2.8 on 2026-07-27 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('car', 'Número do CAR'), ('shapefile', 'Upload de shapefile'), ('coordenadas', 'Coordenadas'), ('demonstrativo', 'PDF — Demonstrativo'), ('recibo', 'PDF — Recibo')], max_length=20)),
                ('car_input', models.CharField(blank=True, default='', max_length=100)),
                ('municipio', models.CharField(blank=True, default='', max_length=150)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('conflitos_count', models.PositiveIntegerField(default=0)),
                ('sucesso', models.BooleanField(default=True)),
                ('erro', models.TextField(blank=True, default='')),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Busca',
                'verbose_name_plural': 'Histórico de Buscas',
                'db_table': 'tb_search_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
