# Generated by Django 5.2.8 on 2026-07-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_type',
            field=models.CharField(choices=[('car', 'Número do CAR'), ('shapefile', 'Upload de shapefile'), ('coordenadas', 'Coordenadas'), ('demonstrativo', 'PDF — Demonstrativo'), ('recibo', 'PDF — Recibo')], db_index=True, max_length=20),
        ),
    ]
