# Generated by Django 5.2.8 on 2026-07-28 00:55

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_searchhistory_search_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Precisa da extensão pg_trgm (CREATE EXTENSION) para os índices GIN
        # abaixo funcionarem. Exige privilégio de superusuário (ou que a
        # extensão já tenha sido criada manualmente por um DBA) no Postgres —
        # se essa migration falhar por permissão, peça para um DBA rodar
        # `CREATE EXTENSION IF NOT EXISTS pg_trgm;` uma vez e rode
        # `manage.py migrate` de novo.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='searchhistory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['car_input'], name='idx_search_car_input_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['municipio'], name='idx_search_municipio_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
