# Generated by Django 5.2.8 on 2026-10-02 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_searchhistory_idx_search_car_input_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Na fila'), ('running', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de cruzamento',
                'verbose_name_plural': 'Lotes de cruzamento',
                'db_table': 'tb_lote_cruzamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=43)),
                ('municipio', models.CharField(blank=True, default='', max_length=150)),
                ('car_status', models.CharField(blank=True, default='', max_length=50)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('points', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Na fila'), ('done', 'Concluído'), ('error', 'Erro')], db_index=True, default='pending', max_length=10)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('overlap_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='analysis.crossbatch')),
            ],
            options={
                'verbose_name': 'CAR do lote de cruzamento',
                'verbose_name_plural': 'CARs do lote de cruzamento',
                'db_table': 'tb_lote_cruzamento_car',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'car_number'), name='uniq_lote_cruzamento_car')],
            },
        ),
    ]
