# Generated by Django 5.2.8 on 2026-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_lote_cruzamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossbatch',
            name='kind',
            field=models.CharField(choices=[('car', 'CARs do SICAR'), ('sigef', 'Parcelas do SIGEF')], default='car', max_length=10),
        ),
        migrations.AddField(
            model_name='crossbatchitem',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_type',
            field=models.CharField(choices=[('car', 'Número do CAR'), ('shapefile', 'Upload de shapefile'), ('coordenadas', 'Coordenadas'), ('demonstrativo', 'PDF — Demonstrativo'), ('recibo', 'PDF — Recibo'), ('sigef', 'Parcela do SIGEF')], db_index=True, max_length=20),
        ),
    ]
