# Generated by Django 5.2.8 on 2025-11-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0002_ruralsettlement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sigef',
            options={'verbose_name': 'Sigef', 'verbose_name_plural': 'Sigef'},
        ),
    ]
