# Generated by Django 5.2.8 on 2025-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0005_remove_ruralsettlement_geometry_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigef',
            name='property_code',
            field=models.CharField(db_column='propriedade_co', max_length=150, verbose_name='Código do imovel'),
        ),
    ]
