# Generated by Django 5.2.8 on 2025-12-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0006_alter_sigef_property_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigef',
            name='installment_code',
            field=models.CharField(db_column='codigo_imo', max_length=150, verbose_name='Código do imovel'),
        ),
        migrations.AlterField(
            model_name='sigef',
            name='status',
            field=models.CharField(db_column='status', max_length=150, verbose_name='Status'),
        ),
    ]
