# Generated by Django 5.2.8 on 2025-12-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0007_alter_sigef_installment_code_alter_sigef_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snictotal',
            name='property_code',
            field=models.CharField(db_column='cod_imovel', max_length=150, verbose_name='Código do imovel'),
        ),
        migrations.AlterField(
            model_name='snictotal',
            name='property_name',
            field=models.CharField(db_column='nome_imove', max_length=150, verbose_name='Nome do imovel'),
        ),
    ]
