# Generated by Django 5.2.8 on 2025-12-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0008_alter_snictotal_property_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigef',
            name='name',
            field=models.CharField(db_column='nome_area', max_length=150, verbose_name='Nome da area'),
        ),
    ]
