# Generated by Django 5.2.8 on 2025-12-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0009_alter_sigef_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigef',
            name='name',
            field=models.CharField(db_column='nome_area', max_length=400, verbose_name='Nome da area'),
        ),
    ]
