# Generated by Django 5.2.8 on 2025-12-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0010_alter_sigef_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigef',
            name='property_code',
            field=models.CharField(blank=True, db_column='propriedade_co', max_length=150, null=True, verbose_name='Código do imovel'),
        ),
    ]
