# Generated by Django 5.2.8 on 2026-10-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0011_alter_sigef_property_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snictotal',
            name='property_name',
            field=models.CharField(db_column='nome_imove', max_length=300, verbose_name='Nome do imovel'),
        ),
    ]
