# Generated by Django 5.2.8 on 2025-12-01 18:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0010_alter_environmentalprotectionarea_geometry_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalprotectionarea',
            name='geometry_new',
        ),
        migrations.RemoveField(
            model_name='indigenousarea',
            name='geometry_new',
        ),
        migrations.RemoveField(
            model_name='phytoecologyarea',
            name='geometry_new',
        ),
        migrations.RemoveField(
            model_name='zoningarea',
            name='geometry_new',
        ),
        migrations.AddField(
            model_name='environmentalprotectionarea',
            name='usable_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674),
        ),
        migrations.AddField(
            model_name='indigenousarea',
            name='usable_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674),
        ),
        migrations.AddField(
            model_name='phytoecologyarea',
            name='usable_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674),
        ),
        migrations.AddField(
            model_name='zoningarea',
            name='usable_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, db_column='geometria_util', null=True, srid=4674),
        ),
    ]
