# Generated by Django 5.2.8 on 2026-10-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_layers', '0011_remove_environmentalprotectionarea_geometry_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phytoecologyarea',
            name='phyto_type',
            field=models.CharField(blank=True, db_column='tipo_fitoecologia', default='', max_length=50, verbose_name='Tipo da Fitoecologia'),
        ),
        migrations.AlterField(
            model_name='phytoecologyarea',
            name='phyto_name',
            field=models.CharField(db_column='nome_fitoecologia', max_length=150, verbose_name='Nome da Fitoecologia'),
        ),
    ]
